version: '3.8'
services:
  app:
    build: .
    ports:
      - "8888:8000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/airline_system
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: airline_system
    ports:
      - "5432:5432"
