version: '3.8'
services:
  app:
    build: .
    ports:
      - "8888:8000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/airline_system
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - db

    volumes:
      - app-data:/app/data

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: airline_system
    ports:
      - "1234:1234"

    
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
    app-data:
    db-data:
